
- name: create a user with passwd
  hosts: itv20 
  remote_user: zhenghz
#  remote_user: lixb
  become: yes
  become_method: su
#  gather_facts: false
  vars:
    user: "zhenghz"
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is your Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$VjAlGZTWtD5t373oLAoTN0
  tasks:
    - name: create {{ user }}
      user: name={{ user }} password={{ password }}
    - name: set up authorized_keys for the deploy user
      authorized_key: user={{ user }} key="{{ lookup('file','~/.ssh/id_rsa.pub')}}"
    - name: config /etc/sudoers
      lineinfile: dest=/etc/sudoers 
                  regexp="{{ user }} ALL"
                  line="{{ user }} ALL=(ALL) ALL"
                  state=present
    - include: linux_config.yml
      
