
- name: create a user "ztest" with passwd
  hosts: Other
  remote_user: lixb #zhenghz
  gather_facts: false
  vars:
    user: "ztest"
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is your Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$a2Gz1vWzqwsuOueisxWcm0
  tasks:
    - name: create {{ user }}
      user: name={{ user }} password={{ password }}
      become: yes
      become_method: su
    - name: set up authorized_keys for the deploy user
      authorized_key: user={{ user }} key="{{ lookup('file','~/.ssh/id_rsa.pub')}}"
      become: yes
      become_method: su
      
