---
- hosts: yk
  remote_user: lixb
  become: yes
  become_method: su
  tasks:
    - name: install the package
      shell: rpm -ivh http://172.20.106.5/zabbix-2.4.7-1.el6.x86_64.rpm; rpm -ivh http://172.20.106.5/zabbix-agent-2.4.7-1.el6.x86_64.rpm
      ignore_errors: yes
    - name: copy the conf file
      copy: src="/home/zhenghz/files/zabbix_agentd.conf" dest="/etc/zabbix/zabbix_agentd.conf"
    - include: add_ip_rules.yml
    - name: start Zabbix agent
      shell: /etc/init.d/zabbix-agent start
  handlers:
    - name: restart iptables
      action: service name=iptables state=restarted
